/**
 * POST /api/auth/qr-exchange
 *
 * Exchanges a one-time QR nonce (generated by /api/auth/qr-login) for a real
 * 30-day JWT token.
 *
 * The Flutter app calls this endpoint after scanning the QR code.
 * Body: { nonce: string }
 *
 * Security properties:
 *  - Nonce is only valid for 2 minutes.
 *  - Nonce can only be consumed once (subsequent calls with same nonce → 401).
 *  - The 30-day token is never embedded in the QR image itself.
 */

import { NextResponse } from 'next/server';
import Admin from '@/lib/models/Admin';
import sequelize from '@/lib/db';
import { createAuthResponse } from '@/lib/auth';
import { consumeNonce } from '@/lib/qr-nonce';
import { checkRateLimit } from '@/lib/rate-limit';

export async function POST(request) {
  // Light rate limiting — 10 attempts per 15 min per IP (prevents nonce brute-force)
  const rl = checkRateLimit(request, `qr-exchange:${
    request.headers.get('x-forwarded-for')?.split(',')[0].trim() || 'unknown'
  }`);
  if (!rl.allowed) {
    return NextResponse.json(
      { success: false, pesan: 'Terlalu banyak percobaan. Coba lagi nanti.' },
      { status: 429, headers: { 'Retry-After': String(rl.retryAfterSec) } },
    );
  }

  try {
    await sequelize.authenticate();

    let body;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ success: false, pesan: 'Body tidak valid.' }, { status: 400 });
    }

    const { nonce } = body ?? {};
    if (!nonce) {
      return NextResponse.json({ success: false, pesan: 'Nonce wajib diisi.' }, { status: 400 });
    }

    // Validate and consume the nonce — single-use, 2-min TTL
    const result = consumeNonce(nonce);
    if (!result.valid) {
      return NextResponse.json({ success: false, pesan: result.reason }, { status: 401 });
    }

    // Fetch the admin the nonce was issued for
    const admin = await Admin.findByPk(result.adminId);
    if (!admin || !admin.is_active) {
      return NextResponse.json(
        { success: false, pesan: 'Akun tidak ditemukan atau sudah dinonaktifkan.' },
        { status: 403 },
      );
    }

    // Issue the real 30-day session token
    const authData = createAuthResponse(admin, '30d');

    return NextResponse.json({
      success: true,
      pesan: 'Login berhasil',
      data: {
        ...authData,
        server_url:      result.serverUrl,
        expires_in_days: 30,
      },
    });
  } catch (error) {
    console.error('QR exchange error:', error);
    return NextResponse.json(
      { success: false, pesan: 'Terjadi kesalahan server.' },
      { status: 500 },
    );
  }
}
